version = 1

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "mocha",
    "vitest"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "rustfmt"