[package]
name = "axolotl"
version = "0.1.0"
edition = "2021"


[build-dependencies]
tauri-build = { version = "1.2.1", features = [], optional = true}

[dependencies]
tauri = { version = "1.2.3", features = [], optional = true }
presage = { git = "https://github.com/nanu-c/presage", rev = "9cc46f343d60b5420e4c1812562c6d933998c332" }
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "456bf6eb2e4454ce35bdb4ca75b8dba7941c2923" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.11"
hex = "0.4"
warp = "0.3"
futures = { version = "0.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.17"
env_logger = "0.10.0"
url = "2.2.2"
sled = "0.34.7"
clap = { version = "4.1.1", features = ["derive"] }
dirs = "4.0.0"
serve-directory = "0.1.0"

[patch.crates-io]
"curve25519-dalek" = { git = 'https://github.com/signalapp/curve25519-dalek', branch = 'lizard2' }


[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
tauri = ["dep:tauri", "custom-protocol"]
ut = []
#![feature(async_closure)]