name: axolotl
version: git
summary: An signal client.
description: |
  Axolotl is a crossplattform signal client

confinement: devmode
base: core18

parts:
  axolotl:
    plugin: go
    go-importpath: github.com/nanu-c/axolotl
    source: .
    source-type: git
    build-packages:
      - gcc
      - mercurial
      - bzr

apps:
  axolotl:
    command: bin/axolotl
    plugs: ["desktop", "desktop-legacy", "home", "x11", "unity7", "browser-support", "network", "gsettings", "pulseaudio", "opengl"]
