name: axolotl
version: git
summary: An signal client.
description: |
  Axolotl is a crossplattform signal client

confinement: devmode
base: core18

parts:
  textsecure:
    plugin: go
    go-importpath: github.com/nanu-c/textsecure-qml
    source: .
    source-type: git
    build-packages:
      - gcc
      - mercurial
      - bzr

apps:
  axolotl:
    command: bin/textsecure-qml
