name: axolotl
version: git
summary: An signal client.
description: |
  Axolotl is a crossplattform signal client

confinement: devmode
grade: devel
base: core18

parts:
  axolotl:
    plugin: go
    go-importpath: github.com/nanu-c/axolotl
    source: .
    source-type: git
    build-packages:
      - gcc
      - mercurial
      - bzr
      - npm
    override-build: |
      cd axolotl-web&&npm install&&npm run build
      echo "This runs before build!"
      snapcraftctl build
apps:
  axolotl:
    command: bin/axolotl
    plugs: ["desktop", "desktop-legacy", "home", "x11", "unity7", "browser-support", "network", "gsettings", "pulseaudio", "opengl"]
