ignores:
  - "sass-loader"
  - "bootstrap"
  - "@vue/cli-plugin-eslint"
  - "@babel/eslint-parser"
  - "@vue/cli-plugin-babel"
  - "browserslist"
  - "vue3-gettext"
  - "@vue/eslint-config-airbnb"
  - "eslint-config-prettier"
  - "eslint-plugin-import"
  - "eslint-plugin-prettier"
  - "eslint-plugin-prettier-vue"
  - "prettier"
  - "sass"
  - "@vue/cli-plugin-unit-mocha"
  - "@vue/compiler-sfc"
  - "autoprefixer"
specials:
  - "bin"
  - "eslint"
skip-missing: true
