name: Axolotl pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  package:
    needs: build
    uses: ./.github/workflows/package.yaml
