name: Axolotl pull request pipeline

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml

  # Check if all important jobs passed
  # This can be used as required status for branch protection rules.
  pr-ok:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
