name: Axolotl pipeline

on: [ push, pull_request ]

jobs:
  build-axolotl:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -race ./...

      - name: Build
        run: go build -v

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: axolotl-${{ matrix.os }}-${{ github.run_number }}
          path: axolotl

  build-axolotl-web:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: npm --prefix ./axolotl-web ci

      - name: Run tests
        run: npm --prefix ./axolotl-web test

      - name: Lint application
        run: npm --prefix ./axolotl-web run lint

      - name: Build
        run: npm --prefix ./axolotl-web run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: axolotl-web-${{ github.run_number }}
          path: axolotl-web/dist/

  package:
    needs: [build-axolotl, build-axolotl-web]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download axolotl build artifacts
        uses: actions/download-artifact@v2
        with:
          path: axolotl

      - name: Download axolotl-web build artifacts
        uses: actions/download-artifact@v2
        with:
          path: axolotl-web

      - name: Display axolotl files
        run: |
          ls -R
          pwd

      - name: Setup appimagetool
        run: |
          curl -sLO https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ln -s appimagetool-x86_64.AppImage /usr/bin/appimagetool

      - name: create an AppImage
        run: |
          rm -rf build/AppDir

          mkdir -p build/AppDir/usr/bin
          cp -f axolotl build/AppDir/usr/bin/axolotl

          mkdir -p build/AppDir/usr/bin/axolotl-web
          cp -rf axolotl-web/dist build/AppDir/usr/bin/axolotl-web

          cp -f appimage/AppDir/AppRun build/AppDir/AppRun
          cp -f appimage/AppDir/axolotl.desktop build/AppDir/axolotl.desktop
          cp -f appimage/AppDir/axolotl.png build/AppDir/axolotl.png

          mkdir -p build/AppDir/usr/share/metainfo
          cp -f appimage/AppDir/axolotl.appdata.xml build/AppDir/usr/share/metainfo/axolotl.appdata.xml

          appimagetool build/AppDir

      - name: Display AppImage files
        run: |
          ls -R
          pwd
