name: Axolotl pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: Execute build workflow
    uses: ./.github/workflows/build.yaml

  package:
    name: Execute package workflow
    needs: build
    uses: ./.github/workflows/package.yaml
