name: Axolotl pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml

  package:
    name: Package
    needs: build
    uses: ./.github/workflows/package.yaml
